---

- name: Update
  become: yes
  apt:
    update_cache=yes

- name: Install system dependencies
  become: yes
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - vim
    - htop
    - iotop
    - wget
    - dstat
    - strace

- name: Install German locale
  become: yes
  locale_gen:
    name=de_DE.UTF-8
    state=present

# XXX use the newer synatx on ansible >= 2.2.0
- name: Set timezone to Europe/Berlin
  become: yes
  shell: timedatectl set-timezone Europe/Berlin
#  timezone:
#    name=Europe/Berlin
