---

- name: Update
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install system dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - htop
    - iotop
    - wget
    - dstat
    - strace

- name: Install German locale
  become: true
  community.general.locale_gen:
    name: de_DE.UTF-8
    state: present

- name: Set timezone to Europe/Berlin
  become: true
  community.general.timezone:
    name: Europe/Berlin
