name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:

  yaml:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install yamllint

      - name: Lint the code
        run: |
          yamllint */*.yml

  playbook:
    name: ansible-playbook lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install ansible

      - name: Lint
        run: |
          ansible-galaxy role install geerlingguy.ntp
          ansible-playbook --syntax-check ansible.yml

  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install ansible-lint

      - name: Lint
        run: |
          ansible-lint .
